version: "3"

services:
  webserver:
    image: node:10
    container_name: gameserver
    volumes: 
    - .:/home/app
    working_dir: /home/app
    ports:
      - "3000:3000"
    command: >
      bash -c "npm install -g nodemon 
      && nodemon app/server.js"