apiVersion: apps/v1
kind: Deployment
metadata:
  name: proy2-pygrpc
  namespace: project
spec:
  selector:
    matchLabels:
      app: pygrpc
  template:
    metadata:
      labels:
        app: pygrpc
    spec:
      containers:
      - name: pygrpc
        image: gcr.io/so1-proy2/pygrpc111:1.0
        ports:
        - containerPort: 50051
