apiVersion: apps/v1
kind: Deployment
metadata:
  name: proy2-frontend
  namespace: frontend
spec:
  replicas: 3
  type: LoadBalancer
  linkerd.io/inject: enabled
  selector:
    matchLabels:
      app: proy2
  template:
    metadata:
      labels:
        app: proy2
    spec:
      containers:
      - name: frontend
        image: gcr.io/so1-proy2/frontend111:1.0
        ports:
        - containerPort: 3000
