kind: Deployment
apiVersion: apps/v1
metadata:
  name: app_web
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app_web
  template:
    metadata:
      labels:
        app: app_web
    spec:
      containers:
        - name: app_web
          image: localhost:3000/app_web
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always