apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_web
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proy2
  template:
    metadata:
      labels:
        app: proy2
    spec:
      containers:
      - name: frontend
        image: us.get.io/so1-proy2/frontdend-appweb-grupo6-v:1.0
        ports:
        - containerPort: 3000
