apiVersion: apps/v1
kind: Deployment
metadata:
  name: aweb
  namespace: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: aweb
    spec:
      containers:
      - name: aweb
        image: us.get.io/so1-proy2/frontdend-appweb-grupo6-v:1.0
        imagePullPolicy: IfNotPrsent
        ports:
        - containerPort: 3000
