kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodeserver
  namespace: frontend
spec:
  replicas: 1
  type: LoadBalancer
  selector:
    matchLabels:
      app: nodeserver
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
        - name: nodeserver
          image: gcr.io/so1-proy2/service-nodejs-grupo6
          imagePullPolicy: Always
          ports:
            - containerPort: 2000
      restartPolicy: Always